# backend/app/api/qa.py

import os
from datetime import datetime
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional, List
from google import genai
from google.genai import types

router = APIRouter(prefix="/api/qa", tags=["qa"])


class QARequest(BaseModel):
    question: str = Field(..., min_length=1)
    politician_ids: Optional[List[str]] = Field(default=None)
    topic: Optional[str] = None


class Claim(BaseModel):
    text: str
    citations: List[str]
    confidence: Optional[float] = None


class Citation(BaseModel):
    source_id: str
    url: str
    title: str
    publisher: str
    retrieved_at: str
    snippet: Optional[str] = None


class QAResponse(BaseModel):
    answer: str
    claims: List[Claim]
    citations: List[Citation]
    limitations: Optional[str] = None
    disclosure: str = "This answer is generated by AI based on available public data. Always verify information independently."


@router.post("/ask", response_model=QAResponse)
async def ask_question(payload: QARequest):
    """
    Simple Q&A endpoint using Gemini API directly (no database required).
    
    This is a simplified version for demo purposes. For production with full
    RAG pipeline including vector search and citation validation, use /api/rag/answer.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")
    
    try:
        client = genai.Client(api_key=api_key)
        
        # Create a prompt that encourages structured responses
        system_prompt = """You are CivicLens AI, a helpful assistant that provides factual information about US politicians and politics.

When answering questions:
- Be concise and factual
- If you're not certain about specific details, acknowledge limitations
- Focus on publicly verifiable information
- Avoid speculation or opinions

Format your response as a clear, structured answer."""

        user_prompt = f"Question: {payload.question}"
        
        if payload.politician_ids:
            user_prompt += f"\n\nContext: This question is about politician(s) with ID(s): {', '.join(payload.politician_ids)}"
        
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"{system_prompt}\n\n{user_prompt}",
            config=types.GenerateContentConfig(
                temperature=0.3,
                max_output_tokens=800,
            )
        )
        
        answer_text = (response.text or "").strip()
        
        if not answer_text:
            answer_text = "I don't have enough information to answer that question."
        
        # Create a mock citation since we're not using the database
        mock_citation = Citation(
            source_id="gemini-ai-1",
            url="https://ai.google.dev/gemini-api",
            title="Gemini AI Response",
            publisher="Google AI",
            retrieved_at=datetime.utcnow().isoformat(),
            snippet="AI-generated response based on training data"
        )
        
        # Create a single claim with the answer
        claim = Claim(
            text=answer_text,
            citations=["gemini-ai-1"],
            confidence=0.7
        )
        
        return QAResponse(
            answer=answer_text,
            claims=[claim],
            citations=[mock_citation],
            limitations="This is a demo response without database integration. Answers are generated by AI and should be verified independently.",
            disclosure="This answer is generated by AI based on available public data. Always verify information independently."
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate AI response: {str(e)}"
        )


__all__ = ["router"]
