# backend/app/api/qa.py

import os
from datetime import datetime
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel, Field
from typing import Optional, List
from google import genai
from google.genai import types
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text

from app.core.database import get_db

router = APIRouter(prefix="/api/qa", tags=["qa"])


class QARequest(BaseModel):
    question: str = Field(..., min_length=1)
    politician_ids: Optional[List[str]] = Field(default=None)
    topic: Optional[str] = None
    use_database: bool = Field(default=True, description="Whether to search database for sources")


class Claim(BaseModel):
    text: str
    citations: List[str]
    confidence: Optional[float] = None


class Citation(BaseModel):
    source_id: str
    url: str
    title: str
    publisher: str
    retrieved_at: str
    snippet: Optional[str] = None
    source_type: str = Field(default="ai_general", description="'database' or 'ai_general'")


class QAResponse(BaseModel):
    answer: str
    claims: List[Claim]
    citations: List[Citation]
    limitations: Optional[str] = None
    disclosure: str = "This answer is generated by AI based on available public data. Always verify information independently."


@router.post("/ask", response_model=QAResponse)
async def ask_question(payload: QARequest, db: AsyncSession = Depends(get_db)):
    """
    Q&A endpoint using Gemini API with optional database source retrieval.
    
    If use_database=True and database sources are found, they will be used.
    Otherwise, falls back to AI general knowledge.
    
    For production with full RAG pipeline including guardrails and validation,
    use /api/rag/answer endpoint.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")
    
    citations = []
    source_type = "ai_general"
    limitations_msg = "This response is generated by AI without access to a specific source database."
    context_text = ""  # Initialize context_text
    
    # Try to retrieve from database if requested
    if payload.use_database:
        try:
            # Try to find relevant sources from database
            # First, generate embedding for the question
            client = genai.Client(api_key=api_key)
            
            # Use text-embedding-004 for consistency with ingestion
            embed_result = client.models.embed_content(
                model="text-embedding-004",
                contents=payload.question,
                config={"output_dimensionality": 768}  # Match database vector dimension
            )
            
            # Extract embedding
            if hasattr(embed_result, "embeddings") and embed_result.embeddings:
                emb = embed_result.embeddings[0]
                query_embedding = list(getattr(emb, "values", None) or getattr(emb, "embedding", None) or emb)
            elif hasattr(embed_result, "embedding"):
                emb = embed_result.embedding
                query_embedding = list(getattr(emb, "values", None) or emb)
            else:
                query_embedding = None
            
            # Search for similar chunks if we have an embedding
            if query_embedding:
                embedding_str = "[" + ",".join(f"{x:.8f}" for x in query_embedding) + "]"
                
                # Query for top 5 most relevant chunks
                query = text("""
                    SELECT 
                        rc.id as chunk_id,
                        rc.text,
                        rs.id as source_id,
                        rs.source_url,
                        rs.title,
                        rs.publisher,
                        rs.source_type,
                        rs.retrieved_at,
                        1 - (rc.embedding <=> CAST(:embedding AS vector)) as similarity
                    FROM rag_chunks rc
                    JOIN rag_sources rs ON rc.source_id = rs.id
                    WHERE rc.embedding IS NOT NULL
                    ORDER BY rc.embedding <=> CAST(:embedding AS vector)
                    LIMIT 5
                """)
                
                result = await db.execute(query, {"embedding": embedding_str})
                rows = result.fetchall()
                
                print(f"🔍 Database search found {len(rows)} results")
                if rows:
                    print(f"   Top similarity: {rows[0][8]:.4f}")
                    print(f"   Top result: {rows[0][4]} - {rows[0][5]}")
                    # Debug: Show all results
                    for i, row in enumerate(rows):
                        print(f"   [{i+1}] {row[8]:.4f} - {row[4]} - {row[1][:100]}...")
                
                # Only use database if we have STRONG match (>= 55% similarity)
                # This prevents using generic sources for specific questions
                if rows and rows[0][8] >= 0.55:
                    # We found relevant sources!
                    source_type = "database"
                    limitations_msg = f"Answer based on {len(rows)} verified source(s) from the CivicLens database."
                    
                    # Build citations
                    seen_sources = set()
                    context_text = ""
                    
                    for row in rows:
                        chunk_id, chunk_text, src_id, url, title, publisher, src_type, retrieved_at, similarity = row
                        
                        if str(src_id) not in seen_sources:
                            citations.append(Citation(
                                source_id=str(src_id),
                                url=url,
                                title=title,
                                publisher=publisher,
                                retrieved_at=retrieved_at.isoformat(),
                                snippet=chunk_text[:200] + "..." if len(chunk_text) > 200 else chunk_text,
                                source_type="database"
                            ))
                            seen_sources.add(str(src_id))
                        
                        context_text += f"\n\nSource: {title}\n{chunk_text}\n"
                else:
                    # Similarity too low - skip database, use AI general knowledge
                    print(f"   ⚠️ Similarity below threshold (55%), using AI general knowledge instead")
        
        except Exception as e:
            print(f"Error querying database: {e}")
            # Fall through to AI general knowledge
    
    try:
        # Generate answer with Gemini
        if context_text:
            # Database sources found - use data extraction mode
            system_prompt = """You are CivicLens AI, a data extraction assistant that finds and presents specific information from provided sources.

Your PRIMARY TASK:
1. CAREFULLY read through ALL provided database sources
2. EXTRACT any specific data that answers the user's question (bills, votes, names, numbers, statistics)
3. Present that extracted data in a clear, structured format
4. DO NOT say "sources don't contain" unless you've checked EVERY source thoroughly

Formatting rules:
- Write in plain text without using markdown formatting (no **, *, #, etc.)
- Use bullet points with • or - for lists
- Include ALL specific details: bill numbers, vote counts, politician names, party affiliations

CRITICAL RULES:
- If database sources mention bill numbers (like H.R. 1834), voting records, or politician names, YOU MUST include them in your answer
- If you find vote counts, party breakdowns, or specific names in the sources, EXTRACT and PRESENT them
- DO NOT ignore data just because it's embedded in a longer paragraph
- Look for patterns like "Yea: X", "Nay: Y", "republicans", "democrats", politician names
- If the information IS in the sources (even partially), use it - don't say it's not there

Format your response as a clear answer using the extracted data."""

            user_prompt = f"Question: {payload.question}"
            
            if payload.politician_ids:
                user_prompt += f"\n\nContext: This question is about politician(s) with ID(s): {', '.join(payload.politician_ids)}"
            
            user_prompt += f"\n\n=== VERIFIED DATABASE SOURCES (READ CAREFULLY) ===\n{context_text}\n=== END OF DATABASE SOURCES ==="
            user_prompt += f"\n\nTASK: Read through ALL the sources above and EXTRACT any information that answers this question: {payload.question}\n"
            user_prompt += "Look for: bill numbers (H.R. XXX), voting records (Yea/Nay counts), politician names, party breakdowns (republicans/democrats), vote tallies, or any related data.\n"
            user_prompt += "IMPORTANT: If the sources contain a LIST of names (like multiple politicians), include ALL of them in your answer, not just the first one.\n"
            user_prompt += "If you find relevant data (even if partial), extract it and present it. DO NOT say information is missing if it's in the sources.\n"
            user_prompt += "Format the data clearly with ALL the specific details you found."
        else:
            # No database sources - use AI general knowledge
            system_prompt = """You are CivicLens AI, a helpful assistant that provides factual information about US politicians and politics.

Since no specific database sources were found for this question, you will use your general knowledge to answer.

Guidelines:
- Be concise and factual
- Write in plain text without using markdown formatting (no **, *, #, etc.)
- DO NOT mention "database sources" or say "sources don't contain" - simply provide the answer
- Focus on publicly verifiable, well-established information
- Avoid speculation, predictions, or opinions
- Use bullet points with • or - for lists
- If unsure about specific details, acknowledge limitations

Format your response as a clear, informative answer using your knowledge."""

            user_prompt = f"Question: {payload.question}"
            
            if payload.politician_ids:
                user_prompt += f"\n\nContext: This question is about politician(s) with ID(s): {', '.join(payload.politician_ids)}"
            
            user_prompt += "\n\nPlease answer this question directly using your general knowledge of US politics and government. Provide a helpful, factual answer without mentioning database sources or limitations."
        
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"{system_prompt}\n\n{user_prompt}",
            config=types.GenerateContentConfig(
                temperature=0.3,
                max_output_tokens=800,
            )
        )
        
        answer_text = (response.text or "").strip()
        
        # Remove markdown formatting if present
        answer_text = answer_text.replace("**", "").replace("__", "")
        
        if not answer_text:
            answer_text = "I don't have enough information to answer that question."
        
        # If no database sources, use AI general knowledge citation
        if not citations:
            citations.append(Citation(
                source_id="ai-knowledge-base",
                url="",
                title="AI Generated Answer",
                publisher="CivicLens AI",
                retrieved_at=datetime.utcnow().isoformat(),
                snippet="Response generated from AI's general knowledge. Not from CivicLens database.",
                source_type="ai_general"
            ))
        
        # Create claim
        claim = Claim(
            text=answer_text,
            citations=[c.source_id for c in citations],
            confidence=0.9 if source_type == "database" else 0.7
        )
        
        return QAResponse(
            answer=answer_text,
            claims=[claim],
            citations=citations,
            limitations=limitations_msg,
            disclosure="This answer is generated by AI. " + (
                "It uses verified sources from the CivicLens database." if source_type == "database"
                else "For more accurate answers with proper citations, add more sources to the database."
            )
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate AI response: {str(e)}"
        )


__all__ = ["router"]
